---
# file: roles/slack/tasks/debug.yml

# Distribution variables

- name: "debug value of ansible_distribution"
  debug: var=ansible_distribution

- name: "debug value of ansible_distribution_version"
  debug: var=ansible_distribution_version

- name: "debug value of ansible_distribution_release"
  debug: var=ansible_distribution_release

- name: "debug value of ansible_lsb.major_release"
  debug: var=ansible_lsb.major_release

# when: ansible_distribution == 'CentOS' and ansible_distribution_version == '6.4'
# when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'
# when: ansible_distribution == 'Debian' and ansible_distribution_version == '7'
# when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 5

