---
# file: project_name/slack.yml

- hosts: slack
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_controller_user="{{ lookup('env','USER') }}"
    - debug: var=fact_controller_user

    - set_fact: fact_controller_home="{{ lookup('env','HOME') }}"
    - debug: var=fact_controller_home

  roles:

    - { role: slack, slack_state: 'absent', slack_ver: '2.0.3' }
    - { role: slack, slack_state: 'present', slack_ver: '2.6.2' }
  
#    - { role: cjsteel.ansible-role-slack, slack_state: 'absent', slack_ver: '2.0.3' }
#    - { role: cjsteel.ansible-role-slack, slack_state: 'present', slack_ver: '2.6.2' }
